name: CI

on:
  schedule:
    - cron: '30 0 * * *' # 9:30(JST)
  push:
    branches: 
      - master

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install poetry
      run: pip install poetry
    - name: Install dependencies
      run: poetry install
    - name: Confirm java runtime
      run: java -version
    - name: Run test
      run: poetry run pytest
